name: automerge

on:
  pull_request:
    branches:
      - main

concurrency:
  group: automerge-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  automerge:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.9.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
          cache: npm
      - name: build actions dist
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          npm run build
          if ! git diff \
            --cached \
            -s \
            --exit-code dist; then
            declare -r sls_mentor_version=$(jq -r '.devDependencies["sls-mentor"]' < package.json)
            git push origin :refs/tags/v"${sls_mentor_version:?}"
            git config user.name 'Github Actions'
            git config user.email '<>'
            git add dist
            git commit -m "chore: build github actions dist"
            git tag v"${sls_mentor_version:?}"
            git push origin
            git push origin v"${sls_mentor_version:?}"
          fi
